/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package porjec_kasir;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class EntriSupplier extends javax.swing.JFrame {
  String driver = "com.mysql.jdbc.Driver";
    String db = "jdbc:mysql://localhost/projectpbo";
    /**
     * Creates new form EntriSupplier
     */
    public EntriSupplier() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataSupllier = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tlpn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kode_supplier = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nama_supplier = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        simpan_sup = new javax.swing.JButton();
        ubah_sup = new javax.swing.JButton();
        reset_sup = new javax.swing.JButton();
        hapus_sub = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSup = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataSupllier.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Entri Data Supplier");

        jLabel11.setText("Kode Supplier");

        jLabel12.setText("Nama Supplier");

        jLabel13.setText("No. Telpon");

        jLabel14.setText("Email");

        jLabel15.setText("Alamat");

        simpan_sup.setText("Simpan");
        simpan_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_supActionPerformed(evt);
            }
        });

        ubah_sup.setText("Ubah");
        ubah_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_supActionPerformed(evt);
            }
        });

        reset_sup.setText("Reset");
        reset_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_supActionPerformed(evt);
            }
        });

        hapus_sub.setText("Hapus");
        hapus_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_subActionPerformed(evt);
            }
        });

        tableSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "No. Telpon", "Email", "Alamat"
            }
        ));
        tableSup.setGridColor(new java.awt.Color(0, 0, 0));
        tableSup.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tableSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSup);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataSupllierLayout = new javax.swing.GroupLayout(dataSupllier);
        dataSupllier.setLayout(dataSupllierLayout);
        dataSupllierLayout.setHorizontalGroup(
            dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataSupllierLayout.createSequentialGroup()
                .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataSupllierLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(dataSupllierLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kode_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataSupllierLayout.createSequentialGroup()
                                    .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tlpn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(193, 193, 193)
                            .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(dataSupllierLayout.createSequentialGroup()
                            .addGap(384, 384, 384)
                            .addComponent(jLabel10))
                        .addGroup(dataSupllierLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(simpan_sup)
                            .addGap(18, 18, 18)
                            .addComponent(ubah_sup)
                            .addGap(18, 18, 18)
                            .addComponent(reset_sup)
                            .addGap(18, 18, 18)
                            .addComponent(hapus_sub))
                        .addGroup(dataSupllierLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataSupllierLayout.setVerticalGroup(
            dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataSupllierLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataSupllierLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset_sup)
                            .addComponent(ubah_sup)
                            .addComponent(simpan_sup)
                            .addComponent(hapus_sub)))
                    .addGroup(dataSupllierLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(kode_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataSupllierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tlpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataSupllier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataSupllier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_supActionPerformed
       String kodeSup = kode_supplier.getText();
       String name = nama_supplier.getText();
        String address = alamat.getText();
        String phone = tlpn.getText();
        String emailSup = email.getText();
    
        // Periksa apakah kode supplier sudah ada di database
        if (supplierExists(kodeSup)) {
        JOptionPane.showMessageDialog(null, "Supplier dengan kode tersebut sudah ada");
        return;
        }
        
        if (kodeSup.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Kode Supplier belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Keluar dari method jika kode barang belum diisi
        }
        
        if (address.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Alamat Supplier belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Keluar dari method jika kode barang belum diisi
        }
        
        if (emailSup.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Email Supplier belum diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Keluar dari method jika kode barang belum diisi
        }
    
        Supplier supplier = new Supplier(kodeSup, name,address, phone, emailSup);
        supplier.save();
        tampilData();

    }//GEN-LAST:event_simpan_supActionPerformed

    private boolean supplierExists(String kodeSup) {
    boolean exists = false;
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projectpbo", "root", "");
         PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM supplier WHERE kode_sup = ?")) {

        ps.setString(1, kodeSup);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            int count = rs.getInt(1);
            exists = count > 0;
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
    return exists;
    }
    
    private void ubah_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_supActionPerformed
     DefaultTableModel table = (DefaultTableModel) tableSup.getModel();
    int selectedRow = tableSup.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih satu baris untuk di-update");
        return;
    }
    
     String kodeSupplierDariTabel = table.getValueAt(selectedRow, 0).toString();
    String kodeSupplierInput = kode_supplier.getText().trim();

    if (!kodeSupplierInput.equals(kodeSupplierDariTabel)) {
        JOptionPane.showMessageDialog(null, "Kode Supplier tidak bisa di ubah", "Warning", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ambil nilai kode supplier dari baris yang dipilih
    String kodeSuplier = table.getValueAt(selectedRow, 0).toString();
    String namaSupplier = nama_supplier.getText().trim();
    String alamat = this.alamat.getText().trim();
    String noHp = tlpn.getText().trim();
    String email = this.email.getText().trim();

    try {
        // Load the MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        // Database connection
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projectpbo", "root", ""); 

        // Perbarui data supplier di database
        String sql = "UPDATE supplier SET nama_sup = ?, tlpn = ?, email = ?, alamat = ? WHERE kode_sup = ?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, namaSupplier);
        stmt.setString(2, noHp);
        stmt.setString(3, email);
        stmt.setString(4, alamat);
        stmt.setString(5, kodeSuplier); // Pastikan ini benar

        int rowsUpdated = stmt.executeUpdate();
        stmt.close();
        conn.close();

        if (rowsUpdated > 0) {
            // Update the row in the GUI table
            table.setValueAt(namaSupplier, selectedRow, 1);
            table.setValueAt(noHp, selectedRow, 2);
            table.setValueAt(email, selectedRow, 3);
            table.setValueAt(alamat, selectedRow, 4);

            JOptionPane.showMessageDialog(null, "Data berhasil di-update");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database");
        }
    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "Driver tidak ditemukan: " + ex.getMessage());
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_ubah_supActionPerformed

    private void reset_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_supActionPerformed
        // TODO add your handling code here:
        
        kode_supplier.setText("");
        nama_supplier.setText("");
        tlpn.setText("");
        email.setText("");
        alamat.setText("");

    }//GEN-LAST:event_reset_supActionPerformed

    private void hapus_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_subActionPerformed

        DefaultTableModel table = (DefaultTableModel) tableSup.getModel();
         if(tableSup.getSelectedRowCount() == 1){
        int selectedRow = tableSup.getSelectedRow();
        String kodeBarang = table.getValueAt(selectedRow, 0).toString(); // Mengambil kode barang dari kolom pertama
        
        // Hapus data dari database
        try {
            Class.forName(driver);
            Connection conn =  (Connection) configDB.config();
            String sql = "DELETE FROM supplier WHERE kode_sup = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, kodeBarang);
            stmt.executeUpdate();
            stmt.close();
            conn.close();
            
            // Hapus baris dari tabel setelah berhasil dihapus dari database
            table.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    } else {
        if(tableSup.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tabel kosong");
        } else {
            JOptionPane.showMessageDialog(null, "Pilih satu baris untuk dihapus");
        }
    }
    }//GEN-LAST:event_hapus_subActionPerformed

    
  
    private void tableSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSupMouseClicked
        // TODO add your handling code here:
        int i = tableSup.getSelectedRow();

        if(i >- 1){
            DefaultTableModel tableModel = (DefaultTableModel) tableSup.getModel();
            kode_supplier.setText(tableModel.getValueAt(i, 0).toString());
            nama_supplier.setText(tableModel.getValueAt(i, 1).toString());
            tlpn.setText(tableModel.getValueAt(i, 2).toString());
            email.setText(tableModel.getValueAt(i, 3).toString());
            alamat.setText(tableModel.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_tableSupMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // untuk menampilakn data dari database supplaier
  private void tampilData() {
        DefaultTableModel table = (DefaultTableModel) tableSup.getModel();
    table.setRowCount(0);
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projectpbo", "root", "")) {
        String query = "SELECT kode_sup, nama_sup, tlpn, email, alamat FROM supplier";
        Statement statement = con.createStatement();
        ResultSet resultSet = statement.executeQuery(query);

        while (resultSet.next()) {
            String kodeSup = resultSet.getString("kode_sup");
            String name = resultSet.getString("nama_sup");
            String phone = resultSet.getString("tlpn");
            String email = resultSet.getString("email");
            String address = resultSet.getString("alamat");
            table.addRow(new Object[]{kodeSup, name, phone, email, address});
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    tableSup.setModel(table);
    }


    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntriSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntriSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntriSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntriSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntriSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JPanel dataSupllier;
    private javax.swing.JTextField email;
    private javax.swing.JButton hapus_sub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField kode_supplier;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JButton reset_sup;
    private javax.swing.JButton simpan_sup;
    private javax.swing.JTable tableSup;
    private javax.swing.JTextField tlpn;
    private javax.swing.JButton ubah_sup;
    // End of variables declaration//GEN-END:variables
}
