/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package porjec_kasir;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        layarDepan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        entriDataBarang = new javax.swing.JMenuItem();
        entriDataSupplier = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        pembelian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        tempatDataBarang = new javax.swing.JMenuItem();
        tempatDataSupplier = new javax.swing.JMenuItem();
        tempatDataPenjualan = new javax.swing.JMenuItem();
        tempatDataPembelian = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        layarDepan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel8.setText("DAKAROH Pizza");

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        jLabel9.setText("Order Sekarang juga!!");

        javax.swing.GroupLayout layarDepanLayout = new javax.swing.GroupLayout(layarDepan);
        layarDepan.setLayout(layarDepanLayout);
        layarDepanLayout.setHorizontalGroup(
            layarDepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarDepanLayout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addGroup(layarDepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layarDepanLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layarDepanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(355, 355, 355))))
        );
        layarDepanLayout.setVerticalGroup(
            layarDepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarDepanLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(256, 256, 256))
        );

        jLayeredPane1.add(layarDepan, "card2");

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setText("Entri Data");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        entriDataBarang.setText("Entri Data Barang");
        entriDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entriDataBarangMouseClicked(evt);
            }
        });
        entriDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriDataBarangActionPerformed(evt);
            }
        });
        jMenu1.add(entriDataBarang);

        entriDataSupplier.setText("Entri Data Supplier");
        entriDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriDataSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(entriDataSupplier);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        jMenu2.add(penjualan);

        pembelian.setText("Pembelian");
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        jMenu2.add(pembelian);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tempat Data");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tempatDataBarang.setText("Tempat Data Barang");
        tempatDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatDataBarangActionPerformed(evt);
            }
        });
        jMenu3.add(tempatDataBarang);

        tempatDataSupplier.setText("Tempat Data Supplier");
        tempatDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatDataSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(tempatDataSupplier);

        tempatDataPenjualan.setText("Tempat Data Penjualan");
        tempatDataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatDataPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(tempatDataPenjualan);

        tempatDataPembelian.setText("Tempat Data Pembelian");
        tempatDataPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatDataPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(tempatDataPembelian);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entriDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriDataBarangActionPerformed
        // TODO add your handling code here:
        dispose();
        new EntriBarang().setVisible(true);
    }//GEN-LAST:event_entriDataBarangActionPerformed

    private void entriDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriDataSupplierActionPerformed
        // TODO add your handling code here:
        dispose();
       new EntriSupplier().setVisible(true);
    }//GEN-LAST:event_entriDataSupplierActionPerformed

    private void entriDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entriDataBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entriDataBarangMouseClicked

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
        dispose();
        new Penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pembelian().setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void tempatDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatDataBarangActionPerformed
        // TODO add your handling code here:
        dispose();
        new TempatBarang().setVisible(true);
    }//GEN-LAST:event_tempatDataBarangActionPerformed

    private void tempatDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatDataSupplierActionPerformed
        // TODO add your handling code here:
        dispose();
        new tempatSupplier().setVisible(true);
    }//GEN-LAST:event_tempatDataSupplierActionPerformed

    private void tempatDataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatDataPenjualanActionPerformed
        // TODO add your handling code here:
        dispose();
        new tempatPenjualan().setVisible(true);
    }//GEN-LAST:event_tempatDataPenjualanActionPerformed

    private void tempatDataPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatDataPembelianActionPerformed
        // TODO add your handling code here:
        dispose();
        new tempatPembelian().setVisible(true);
    }//GEN-LAST:event_tempatDataPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem entriDataBarang;
    private javax.swing.JMenuItem entriDataSupplier;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel layarDepan;
    private javax.swing.JMenuItem pembelian;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JMenuItem tempatDataBarang;
    private javax.swing.JMenuItem tempatDataPembelian;
    private javax.swing.JMenuItem tempatDataPenjualan;
    private javax.swing.JMenuItem tempatDataSupplier;
    // End of variables declaration//GEN-END:variables
}
